/*
, * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author regina
 */
public class Login extends javax.swing.JFrame {
    //variables para enviar datos a interfaces
    public static String user="";
    String pass = "";
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(956,507);
        //para evitar que el usuario modifique las dimenciones
        setResizable(false);
        setTitle("Login de acceso");
        setLocationRelativeTo(null);
        
        //crear objeto de la clase imagen icon
        ImageIcon wallpaper = new ImageIcon("src/images/playa.jpg");
        Icon icono= new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(),Image.SCALE_DEFAULT));  
        jLabelWallpaper.setIcon(icono);
       //asegurar que actualice la imagen
        this.repaint();
        
        
        //crear objeto
        ImageIcon wallpaperLogo=new ImageIcon("src/images/LogoHotel.png");
        Icon iconoLogo=new ImageIcon(wallpaperLogo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_DEFAULT));
        jLabelLogo.setIcon(iconoLogo);
        this.repaint();
        
             
        
    }//cierre del constructor
    //vamos a sobre escribir un metodo , colocamos @override 
 @Override
        public Image getIconImage(){
        //objeto
        Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.jpeg"));
        return retValue;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonAcceder = new javax.swing.JButton();
        jLabelFooter = new javax.swing.JLabel();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        jTextFieldUser.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldUser.setFont(new java.awt.Font("C059", 0, 24)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 240, 50));

        jPasswordFieldPassword.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordFieldPassword.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        jPasswordFieldPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 287, 240, 60));

        jButtonAcceder.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAcceder.setFont(new java.awt.Font("FreeMono", 0, 24)); // NOI18N
        jButtonAcceder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 50));

        jLabelFooter.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelFooter.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFooter.setText("Creado por grupo mar derechos reservados");
        getContentPane().add(jLabelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 460, -1));
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
    user = jTextFieldUser.getText().trim();
    pass=jPasswordFieldPassword.getText().trim();
    
    //valdacion
    //si el nombre de usuario es diferente al pass ejecutar
        if (!user.equals("") || ! pass.equals("")) {
            try {
               Connection cn= Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement("select ");
            } catch (Exception e) {
                System.err.println("Error en el boton acceder"+e);
                JOptionPane.showMessageDialog(null, "Error al iniciar la sesion , favor de contactar al admin.");

                
            }
 
            
        }else{
        JOptionPane.showMessageDialog(null, "NECESITAS LLENAR TODOS LOS CAMPOS \n   INTENTA DE NUEVO");
        
        }
    
    }//GEN-LAST:event_jButtonAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabelFooter;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
