/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registros;

import controlMySql.MySqlConn;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class Consultas extends javax.swing.JFrame {

    MySqlConn objconn = new MySqlConn();
    MySqlConn conn;
    int total;
    int contadors,contadord,contadort;

    public Consultas(MySqlConn conn) {
        this.conn = conn;
        initComponents();
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jLabel8.setVisible(false);
        this.jLabel9.setVisible(false);
        this.jLabel10.setVisible(false);
        this.jLabel11.setVisible(false);
        this.jLabel12.setVisible(false);
        this.jLabel13.setVisible(false);
        

    }

    public Consultas() {
        initComponents();
    }

    
    boolean bandera = false;
    boolean bandera2 = false;
    boolean bandera3 = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonbuscar2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Porcentaje de ocupacion del hotel");

        jButton2.setText("Mostar uso del hotel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Status del hotel", jPanel3);

        jButton1.setText("Imprimir tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Piso 1");

        jLabel2.setText("Piso 2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(144, 144, 144))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jButton1)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Tipos de Habitaciones", jPanel4);

        jButton3.setText("Mostar Ocupacion Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Sencilla:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Doble:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Triple:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("$800");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("$1000");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("$1300");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setText("Costos por Habitacion y persona Extra");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(759, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(127, 127, 127))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Ocupacion Total ", jPanel5);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hab", "Nombre", "Ciudad", "F.Ingreso", "Piso", "TipoHab", "Ocupantes", "OcupantesExtra", "Costos", "CargosExtra"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(898, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(64, 64, 64))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(34, 34, 34))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Total de Hab", jPanel6);

        jLabel4.setText("Nombre del Huesped");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jButtonbuscar.setText("Buscar");
        jButtonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Habitacion", "Piso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Numero de Habitacion");

        jButtonbuscar2.setText("Buscar");
        jButtonbuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscar2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Habitacion Disponible");

        jLabel7.setText("Habitacion No disponible");

        jLabel15.setText("Piso deseado");

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Habitacion", "Piso"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jButtonbuscar))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel15))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(jTextField2))
                            .addGap(42, 42, 42)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonbuscar2)
                                .addComponent(jButton5)))))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonbuscar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel15))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jTabbedPane1.addTab("Consulta Nombre", jPanel7);

        jButton6.setText("Volver al menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscar2ActionPerformed
        // TODO add your handling code here:

        String query = "select * from huespedes where hab= " + "'" + this.jTextField1.getText().trim() + "'";
        this.conn.Consult(query);
        try {
            int total = this.conn.rs.getInt(4);
            System.out.println(total);
            if (total >0 ) {
                this.jLabel7.setVisible(true);
                 this.jLabel6.setVisible(false);
            }
            
               
            
              

        } catch (SQLException ex) {
             this.jLabel6.setVisible(true);
               this.jLabel7.setVisible(false); 
            
        }

    }//GEN-LAST:event_jButtonbuscar2ActionPerformed

    private void jButtonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscarActionPerformed
        // TODO add your handling code here:
        this.eliminar();
        String query = "select * from huespedes where nombre= " + "'" + this.jTextFieldNombre.getText().trim() + "'";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception ex) {
            System.out.println("Error");
        }
        if (n != 0) {
            Object datos[][] = new Object[n][3];
            for (int i = 0; i < n; i++) {
                try {
                    datos[i][0] = this.conn.rs.getString(1);
                    datos[i][1] = this.conn.rs.getInt(11);
                    datos[i][2] = this.conn.rs.getInt(10);

                    this.conn.rs.next();
                } catch (Exception ex) {
                    System.out.println("error 2");
                }
            }
            String columnas[] = {"Nombre", "Hab", "Piso"};
            jTable1.setModel(new DefaultTableModel(datos, columnas));
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos");
        }

    }//GEN-LAST:event_jButtonbuscarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
        this.jLabel8.setVisible(true);
        this.jLabel9.setVisible(true);
        this.jLabel10.setVisible(true);
        this.jLabel11.setVisible(true);
        this.jLabel12.setVisible(true);
        this.jLabel13.setVisible(true);
        bandera3 = true;
        bandera2 = false;
        bandera = false;
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bandera = true;
        bandera2 = false;
        bandera3 = false;
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bandera2 = true;
        bandera = false;
        bandera3 = false;
        repaint();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:}
        contadors=0;
        contadord=0;
        contadort=0;
        
        this.eliminar();
        String query = "select * from huespedes ORDER BY nombre ASC";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception ex) {
            System.out.println("Error");
        }
        if (n != 0) {
            Object datos[][] = new Object[n][13];
            for (int i =0; i < n; i++) {
                try {
                    datos[i][0] = this.conn.rs.getString(1);
                    datos[i][1] = this.conn.rs.getString(2);
                    datos[i][2] = this.conn.rs.getString(3);
                    datos[i][3] = this.conn.rs.getInt(4);
                    datos[i][4] = this.conn.rs.getInt(5);
                    datos[i][5] = this.conn.rs.getString(6);
                    datos[i][6] = this.conn.rs.getString(7);
                    datos[i][7] = this.conn.rs.getString(8);
                    datos[i][8] = this.conn.rs.getString(9);
                    datos[i][9] = this.conn.rs.getInt(10);
                    datos[i][10] = this.conn.rs.getInt(11);
                    int valor=this.conn.rs.getInt(12);
                    int valor2=this.conn.rs.getInt(13);
                    int valor3=this.conn.rs.getInt(14);
                    
                    
                    if(valor==1){
                        contadors=contadors+1;
                    }
                      if(valor2==1){
                        contadord=contadord+1;
                    }
                    if(valor3==1){
                        contadort=contadort+1;
                    }
                    
                    System.out.println(contadors);
                    System.out.println(contadord);
                    System.out.println(contadort);
                    
                    
                    
                    this.conn.rs.next();
                } catch (Exception ex) {
                    System.out.println("error 2");
                }
            }
            String columnas[] = { "Nombre","TipoHab", "Ciudad","Ocupantes","total dias ", "OcupantesExtra","F.ingreos","F.salida","CargosExtra","Piso","Hab"};
            jTable2.setModel(new DefaultTableModel(datos,columnas));
        } else
            JOptionPane.showMessageDialog(this, "No hay datos");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           this.eliminar();
        String query = "select * from huespedes where piso= " + "'" + this.jTextField2.getText().trim() + "'";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception ex) {
            System.out.println("Error");
        }
        if (n != 0) {
            Object datos[][] = new Object[n][3];
            for (int i = 0; i < n; i++) {
                try {
                    datos[i][0] = this.conn.rs.getString(1);
                    datos[i][1] = this.conn.rs.getInt(11);
                    datos[i][2] = this.conn.rs.getInt(10);

                    this.conn.rs.next();
                } catch (Exception ex) {
                    System.out.println("error 2");
                }
            }
            String columnas[] = {"Nombre", "Hab", "Piso"};
            jTable3.setModel(new DefaultTableModel(datos, columnas));
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu al= new Menu();
        al.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void calculototal() {
        String query = "select * from datos where Hab=";
        this.conn.Consult(query);
        int n = 0;
        try {
            int totalcosE = this.conn.rs.getInt(10);
            int totalcos = this.conn.rs.getInt(11);
            total = totalcosE + totalcos;
        } catch (Exception ex) {
            System.out.println("Error");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonbuscar;
    private javax.swing.JButton jButtonbuscar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void eliminar() {
        DefaultTableModel tb = (DefaultTableModel) this.jTable1.getModel();
        int a = this.jTable1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }

    }

    public void paint(Graphics g) {
        super.paint(g);
        if (bandera == true) {
            int hab_sencilla = 6;
            int hab_doble = 5;
            int hab_triple = 4;

            int totalhab = hab_sencilla + hab_doble + hab_triple;
            int grados_senc = hab_sencilla * 360 / totalhab;
            int grados_doble = hab_doble * 360 / totalhab;
            int grados_triple = hab_triple * 360 / totalhab;

            int hab_sencilla2 = 4;
            int hab_doble2 = 5;
            int hab_triple2 = 6;

            int totalhab2 = hab_sencilla2 + hab_doble2 + hab_triple2;
            int grados_senc2 = hab_sencilla2 * 360 / totalhab2;
            int grados_doble2 = hab_doble2 * 360 / totalhab2;
            int grados_triple2 = hab_triple2 * 360 / totalhab2;

            g.setColor(new Color(255, 0, 0));
            g.fillArc(50, 150, 200, 200, 0, grados_senc);
            g.fillRect(300, 220, 20, 20);
            g.drawString("Habitaciones Sencillas(6)", 340, 235);

            g.setColor(new Color(0, 130, 0));
            g.fillArc(50, 150, 200, 200, grados_senc, grados_doble);
            g.fillRect(300, 250, 20, 20);
            g.drawString("Habitaciones Dobles(5)", 340, 265);

            g.setColor(new Color(0, 0, 130));
            g.fillArc(50, 150, 200, 200, grados_senc + grados_doble, grados_triple);
            g.fillRect(300, 280, 20, 20);
            g.drawString("Habitaciones Triples(4)", 340, 295);

            g.setColor(new Color(255, 0, 0));
            g.fillArc(500, 150, 200, 200, 0, grados_senc2);
            g.fillRect(730, 220, 20, 20);
            g.drawString("Habitaciones Sencillas(4)", 770, 235);

            g.setColor(new Color(0, 130, 0));
            g.fillArc(500, 150, 200, 200, grados_senc2, grados_doble2);
            g.fillRect(730, 250, 20, 20);
            g.drawString("Habitaciones dobles(5)", 770, 265);

            g.setColor(new Color(0, 0, 130));
            g.fillArc(500, 150, 200, 200, grados_senc2 + grados_doble2, grados_triple2);
            g.fillRect(730, 280, 20, 20);
            g.drawString("Habitaciones Triples(6)", 770, 295);

        }
        if (bandera2 == true) {
            int sencilla =contadors;
            int doble =contadord;
            int triple = contadort;
            int totals = 10;
            int totald = 10;
            int totalt = 10;

            int largo_sen = sencilla * 400 / totals;
            int largo_doble = doble * 400 / totald;
            int largo_triple = triple * 400 / totalt;

            int por_s = sencilla * 100 / totals;
            int por_d = doble * 100 / totald;
            int por_t = triple * 100 / totalt;

            g.setColor(new Color(255, 0, 0));
            g.fillRect(50, 120, largo_sen, 50);
            g.setColor(new Color(255, 255, 255));
            g.drawString(por_s + "% de las Hab ocupadas", 55, 140);

            g.setColor(new Color(0, 135, 0));
            g.fillRect(50, 220, largo_doble, 50);
            g.setColor(new Color(255, 255, 255));
            g.drawString(por_d + "% de las Hab ocupadas", 55, 240);

            g.setColor(new Color(0, 0, 255));
            g.fillRect(50, 320, largo_triple, 50);
            g.setColor(new Color(255, 255, 255));
            g.drawString(por_t + "% de las Hab ocupadas", 55, 340);
        }
        if (bandera3 == true) {
            int habTotal = contadors + contadord + contadort;
            int grados_senc2 = habTotal * 360 / 30;
            int restante = 360 - grados_senc2;
            g.setColor(new Color(255, 0, 0));
            g.fillArc(700, 150, 200, 200, 0, grados_senc2);
            g.fillRect(490, 220, 20, 20);
            g.drawString("Habitaciones Ocupadas"+habTotal, 510, 235);
            g.setColor(new Color(255, 255, 255));
            g.fillArc(700, 150, 200, 200, grados_senc2, restante);
            g.fillRect(490, 270, 20, 20);
            g.drawString("Habitaciones Disponibles", 510, 285);

        }
    }
}
